### PR TITLE
Acknowledge EU support

### PR DESCRIPTION
**Pull request by nthiery**

### CODE REVIEW

**Comment by videlec** [comment]
The description of this repo says explicitely

    www.sagemath.org files - edit the website repository, not this one here! 

The relevant repo is https://github.com/sagemath/website and  you can have a look at my pull request at https://github.com/sagemath/website/pull/108

**Comment by haraldschilly** [comment]
oh yes, the website is autogenerated and this repo here is only used to serve the generated files.

**Comment by nthiery** [comment]
Oops, I had missed that. Thanks Vincent for spotting/fixing this and Harald for the merge!

**Comment by haraldschilly** [comment]
here is the latest commit here after applying the PR https://github.com/sagemath/website/pull/108: 

https://github.com/sagemath/sagemath.github.io/commit/69ce688198a0070d5bd1b2a53738c49c4b4032bd

after running the script to publish it

**Pull request closed without merging**
