### PR TITLE
minor ui fix in help_groups.html

### PR DESCRIPTION
**Pull request by cool-man-vk**

### CODE REVIEW

**Comment by haraldschilly** [comment]
This repo is not the source, you have to fix it here: https://github.com/sagemath/website

If you really want to help with the website, there are a couple of papers to add for the publications page: https://github.com/sagemath/publications/issues

**Comment by haraldschilly** [comment]
Besides that, the padding is controlled via css classes, not hardcoded style tags.

**Comment by cool-man-vk** [comment]
But theres no classname for the specific line

**Comment by cool-man-vk** [comment]
I mean the div tag,its better to be hardcoded since it looks good in all
kind of devices

**Comment by haraldschilly** [comment]
I don't know what you mean by "classname for the specific line". For the future and in general, I really recommend you start a ticket in the correct repository and then state the problem.

**Pull request closed without merging**
